<?php

define( 'FIRSTFRAME_ROOT', get_template_directory_uri() );
define( 'FIRSTFRAME_ROOT_DIR', get_template_directory() );
define( 'FIRSTFRAME_ASSETS_ROOT', FIRSTFRAME_ROOT . '/assets' );
define( 'FIRSTFRAME_ASSETS_ROOT_DIR', FIRSTFRAME_ROOT_DIR . '/assets' );
define( 'FIRSTFRAME_ASSETS_CSS_ROOT', FIRSTFRAME_ASSETS_ROOT . '/css' );
define( 'FIRSTFRAME_ASSETS_CSS_ROOT_DIR', FIRSTFRAME_ASSETS_ROOT_DIR . '/css' );
define( 'FIRSTFRAME_ASSETS_JS_ROOT', FIRSTFRAME_ASSETS_ROOT . '/js' );
define( 'FIRSTFRAME_ASSETS_JS_ROOT_DIR', FIRSTFRAME_ASSETS_ROOT_DIR . '/js' );
define( 'FIRSTFRAME_INC_ROOT', FIRSTFRAME_ROOT . '/inc' );
define( 'FIRSTFRAME_INC_ROOT_DIR', FIRSTFRAME_ROOT_DIR . '/inc' );
